// _normalise.mjs - one-off cleanup after route-line-to-field.mjs
// Removes the per-file generated-style trailers that the first version of that
// script appended, and normalises the two font tokens (BOLD / Bold) that it
// produced into a single shared style.
import fs from 'node:fs';
import path from 'node:path';

const DIR = 'tdl';
let trailers = 0, renamed = 0;
for (const f of fs.readdirSync(DIR).filter((x) => x.endsWith('.tdl'))) {
  const p = path.join(DIR, f);
  let s = fs.readFileSync(p, 'utf8');
  const before = s;
  // NB: `\Z` is not a JavaScript regex anchor - it matches a literal "Z".
  s = s.replace(/\n*; --- styles generated by route-line-to-field\.mjs[\s\S]*/, '\n');
  if (s !== before) trailers++;
  const n = (s.match(/JpFontBOLD/g) || []).length;
  if (n) renamed += n;
  s = s.replace(/JpFontBOLD/g, 'JpFontBold');
  fs.writeFileSync(p, s);
}
console.log(`trailers removed from ${trailers} file(s); ${renamed} JpFontBOLD reference(s) normalised`);